const VERSIONS_DIMENSIONS:{
    [versione:number]:{
        [errorCorrection in ErrorCorrection]?:{
            [encodingMode in EncodingMode]?: number
        }
    }
} 
    = {
    1: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 41, [EncodingMode.ALFANUMERIC]: 25, [EncodingMode.BYTE]: 17, [EncodingMode.KANJI]: 10 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 34, [EncodingMode.ALFANUMERIC]: 20, [EncodingMode.BYTE]: 14, [EncodingMode.KANJI]: 8 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 27, [EncodingMode.ALFANUMERIC]: 16, [EncodingMode.BYTE]: 11, [EncodingMode.KANJI]: 7 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 17, [EncodingMode.ALFANUMERIC]: 10, [EncodingMode.BYTE]: 7, [EncodingMode.KANJI]: 4 } },
    2: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 77, [EncodingMode.ALFANUMERIC]: 47, [EncodingMode.BYTE]: 32, [EncodingMode.KANJI]: 20 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 63, [EncodingMode.ALFANUMERIC]: 38, [EncodingMode.BYTE]: 26, [EncodingMode.KANJI]: 16 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 48, [EncodingMode.ALFANUMERIC]: 29, [EncodingMode.BYTE]: 20, [EncodingMode.KANJI]: 12 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 34, [EncodingMode.ALFANUMERIC]: 20, [EncodingMode.BYTE]: 14, [EncodingMode.KANJI]: 8 } },
    3: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 127, [EncodingMode.ALFANUMERIC]: 77, [EncodingMode.BYTE]: 53, [EncodingMode.KANJI]: 32 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 101, [EncodingMode.ALFANUMERIC]: 61, [EncodingMode.BYTE]: 42, [EncodingMode.KANJI]: 26 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 77, [EncodingMode.ALFANUMERIC]: 47, [EncodingMode.BYTE]: 32, [EncodingMode.KANJI]: 20 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 58, [EncodingMode.ALFANUMERIC]: 35, [EncodingMode.BYTE]: 24, [EncodingMode.KANJI]: 15 } },
    4: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 187, [EncodingMode.ALFANUMERIC]: 114, [EncodingMode.BYTE]: 78, [EncodingMode.KANJI]: 48 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 149, [EncodingMode.ALFANUMERIC]: 90, [EncodingMode.BYTE]: 62, [EncodingMode.KANJI]: 38 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 111, [EncodingMode.ALFANUMERIC]: 67, [EncodingMode.BYTE]: 46, [EncodingMode.KANJI]: 28 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 82, [EncodingMode.ALFANUMERIC]: 50, [EncodingMode.BYTE]: 34, [EncodingMode.KANJI]: 21 } },
    5: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 255, [EncodingMode.ALFANUMERIC]: 154, [EncodingMode.BYTE]: 106, [EncodingMode.KANJI]: 65 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 202, [EncodingMode.ALFANUMERIC]: 122, [EncodingMode.BYTE]: 84, [EncodingMode.KANJI]: 52 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 144, [EncodingMode.ALFANUMERIC]: 87, [EncodingMode.BYTE]: 60, [EncodingMode.KANJI]: 37 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 106, [EncodingMode.ALFANUMERIC]: 64, [EncodingMode.BYTE]: 44, [EncodingMode.KANJI]: 27 } },
    6: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 322, [EncodingMode.ALFANUMERIC]: 195, [EncodingMode.BYTE]: 134, [EncodingMode.KANJI]: 82 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 255, [EncodingMode.ALFANUMERIC]: 154, [EncodingMode.BYTE]: 106, [EncodingMode.KANJI]: 65 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 178, [EncodingMode.ALFANUMERIC]: 108, [EncodingMode.BYTE]: 74, [EncodingMode.KANJI]: 45 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 139, [EncodingMode.ALFANUMERIC]: 84, [EncodingMode.BYTE]: 58, [EncodingMode.KANJI]: 36 } },
    7: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 370, [EncodingMode.ALFANUMERIC]: 224, [EncodingMode.BYTE]: 154, [EncodingMode.KANJI]: 95 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 293, [EncodingMode.ALFANUMERIC]: 178, [EncodingMode.BYTE]: 122, [EncodingMode.KANJI]: 75 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 207, [EncodingMode.ALFANUMERIC]: 125, [EncodingMode.BYTE]: 86, [EncodingMode.KANJI]: 53 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 154, [EncodingMode.ALFANUMERIC]: 93, [EncodingMode.BYTE]: 64, [EncodingMode.KANJI]: 39 } },
    8: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 461, [EncodingMode.ALFANUMERIC]: 279, [EncodingMode.BYTE]: 192, [EncodingMode.KANJI]: 118 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 365, [EncodingMode.ALFANUMERIC]: 221, [EncodingMode.BYTE]: 152, [EncodingMode.KANJI]: 93 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 259, [EncodingMode.ALFANUMERIC]: 157, [EncodingMode.BYTE]: 108, [EncodingMode.KANJI]: 66 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 202, [EncodingMode.ALFANUMERIC]: 122, [EncodingMode.BYTE]: 84, [EncodingMode.KANJI]: 52 } },
    9: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 552, [EncodingMode.ALFANUMERIC]: 335, [EncodingMode.BYTE]: 230, [EncodingMode.KANJI]: 141 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 432, [EncodingMode.ALFANUMERIC]: 262, [EncodingMode.BYTE]: 180, [EncodingMode.KANJI]: 111 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 312, [EncodingMode.ALFANUMERIC]: 189, [EncodingMode.BYTE]: 130, [EncodingMode.KANJI]: 80 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 235, [EncodingMode.ALFANUMERIC]: 143, [EncodingMode.BYTE]: 98, [EncodingMode.KANJI]: 60 } },
    10: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 652, [EncodingMode.ALFANUMERIC]: 395, [EncodingMode.BYTE]: 271, [EncodingMode.KANJI]: 167 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 513, [EncodingMode.ALFANUMERIC]: 311, [EncodingMode.BYTE]: 213, [EncodingMode.KANJI]: 131 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 364, [EncodingMode.ALFANUMERIC]: 221, [EncodingMode.BYTE]: 151, [EncodingMode.KANJI]: 93 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 288, [EncodingMode.ALFANUMERIC]: 174, [EncodingMode.BYTE]: 119, [EncodingMode.KANJI]: 74 } },
    11: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 772, [EncodingMode.ALFANUMERIC]: 468, [EncodingMode.BYTE]: 321, [EncodingMode.KANJI]: 198 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 604, [EncodingMode.ALFANUMERIC]: 366, [EncodingMode.BYTE]: 251, [EncodingMode.KANJI]: 155 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 427, [EncodingMode.ALFANUMERIC]: 259, [EncodingMode.BYTE]: 177, [EncodingMode.KANJI]: 109 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 331, [EncodingMode.ALFANUMERIC]: 200, [EncodingMode.BYTE]: 137, [EncodingMode.KANJI]: 85 } },
    12: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 883, [EncodingMode.ALFANUMERIC]: 535, [EncodingMode.BYTE]: 367, [EncodingMode.KANJI]: 226 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 691, [EncodingMode.ALFANUMERIC]: 419, [EncodingMode.BYTE]: 287, [EncodingMode.KANJI]: 177 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 489, [EncodingMode.ALFANUMERIC]: 296, [EncodingMode.BYTE]: 203, [EncodingMode.KANJI]: 125 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 374, [EncodingMode.ALFANUMERIC]: 227, [EncodingMode.BYTE]: 155, [EncodingMode.KANJI]: 96 } },
    13: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 1022, [EncodingMode.ALFANUMERIC]: 619, [EncodingMode.BYTE]: 425, [EncodingMode.KANJI]: 262 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 796, [EncodingMode.ALFANUMERIC]: 483, [EncodingMode.BYTE]: 331, [EncodingMode.KANJI]: 204 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 580, [EncodingMode.ALFANUMERIC]: 352, [EncodingMode.BYTE]: 241, [EncodingMode.KANJI]: 149 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 427, [EncodingMode.ALFANUMERIC]: 259, [EncodingMode.BYTE]: 177, [EncodingMode.KANJI]: 109 } },
    14: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 1101, [EncodingMode.ALFANUMERIC]: 667, [EncodingMode.BYTE]: 458, [EncodingMode.KANJI]: 282 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 871, [EncodingMode.ALFANUMERIC]: 528, [EncodingMode.BYTE]: 362, [EncodingMode.KANJI]: 223 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 621, [EncodingMode.ALFANUMERIC]: 376, [EncodingMode.BYTE]: 258, [EncodingMode.KANJI]: 159 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 468, [EncodingMode.ALFANUMERIC]: 283, [EncodingMode.BYTE]: 194, [EncodingMode.KANJI]: 120 } },
    15: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 1250, [EncodingMode.ALFANUMERIC]: 758, [EncodingMode.BYTE]: 520, [EncodingMode.KANJI]: 320 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 991, [EncodingMode.ALFANUMERIC]: 600, [EncodingMode.BYTE]: 412, [EncodingMode.KANJI]: 254 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 703, [EncodingMode.ALFANUMERIC]: 426, [EncodingMode.BYTE]: 292, [EncodingMode.KANJI]: 180 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 530, [EncodingMode.ALFANUMERIC]: 321, [EncodingMode.BYTE]: 220, [EncodingMode.KANJI]: 136 } },
    16: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 1408, [EncodingMode.ALFANUMERIC]: 854, [EncodingMode.BYTE]: 586, [EncodingMode.KANJI]: 361 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 1082, [EncodingMode.ALFANUMERIC]: 656, [EncodingMode.BYTE]: 450, [EncodingMode.KANJI]: 277 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 775, [EncodingMode.ALFANUMERIC]: 470, [EncodingMode.BYTE]: 322, [EncodingMode.KANJI]: 198 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 602, [EncodingMode.ALFANUMERIC]: 365, [EncodingMode.BYTE]: 250, [EncodingMode.KANJI]: 154 } },
    17: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 1548, [EncodingMode.ALFANUMERIC]: 938, [EncodingMode.BYTE]: 644, [EncodingMode.KANJI]: 397 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 1212, [EncodingMode.ALFANUMERIC]: 734, [EncodingMode.BYTE]: 504, [EncodingMode.KANJI]: 310 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 876, [EncodingMode.ALFANUMERIC]: 531, [EncodingMode.BYTE]: 364, [EncodingMode.KANJI]: 224 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 674, [EncodingMode.ALFANUMERIC]: 408, [EncodingMode.BYTE]: 280, [EncodingMode.KANJI]: 173 } },
    18: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 1725, [EncodingMode.ALFANUMERIC]: 1046, [EncodingMode.BYTE]: 718, [EncodingMode.KANJI]: 442 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 1346, [EncodingMode.ALFANUMERIC]: 816, [EncodingMode.BYTE]: 560, [EncodingMode.KANJI]: 345 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 948, [EncodingMode.ALFANUMERIC]: 574, [EncodingMode.BYTE]: 394, [EncodingMode.KANJI]: 243 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 746, [EncodingMode.ALFANUMERIC]: 452, [EncodingMode.BYTE]: 310, [EncodingMode.KANJI]: 191 } },
    19: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 1903, [EncodingMode.ALFANUMERIC]: 1153, [EncodingMode.BYTE]: 792, [EncodingMode.KANJI]: 488 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 1500, [EncodingMode.ALFANUMERIC]: 909, [EncodingMode.BYTE]: 624, [EncodingMode.KANJI]: 384 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1063, [EncodingMode.ALFANUMERIC]: 644, [EncodingMode.BYTE]: 442, [EncodingMode.KANJI]: 272 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 813, [EncodingMode.ALFANUMERIC]: 493, [EncodingMode.BYTE]: 338, [EncodingMode.KANJI]: 208 } },
    20: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 2061, [EncodingMode.ALFANUMERIC]: 1249, [EncodingMode.BYTE]: 858, [EncodingMode.KANJI]: 528 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 1600, [EncodingMode.ALFANUMERIC]: 970, [EncodingMode.BYTE]: 666, [EncodingMode.KANJI]: 410 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1159, [EncodingMode.ALFANUMERIC]: 702, [EncodingMode.BYTE]: 482, [EncodingMode.KANJI]: 297 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 919, [EncodingMode.ALFANUMERIC]: 557, [EncodingMode.BYTE]: 382, [EncodingMode.KANJI]: 235 } },
    21: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 2232, [EncodingMode.ALFANUMERIC]: 1352, [EncodingMode.BYTE]: 929, [EncodingMode.KANJI]: 572 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 1708, [EncodingMode.ALFANUMERIC]: 1035, [EncodingMode.BYTE]: 711, [EncodingMode.KANJI]: 438 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1224, [EncodingMode.ALFANUMERIC]: 742, [EncodingMode.BYTE]: 509, [EncodingMode.KANJI]: 314 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 969, [EncodingMode.ALFANUMERIC]: 587, [EncodingMode.BYTE]: 403, [EncodingMode.KANJI]: 248 } },
    22: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 2409, [EncodingMode.ALFANUMERIC]: 1460, [EncodingMode.BYTE]: 1003, [EncodingMode.KANJI]: 618 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 1872, [EncodingMode.ALFANUMERIC]: 1134, [EncodingMode.BYTE]: 779, [EncodingMode.KANJI]: 480 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1358, [EncodingMode.ALFANUMERIC]: 823, [EncodingMode.BYTE]: 565, [EncodingMode.KANJI]: 348 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1056, [EncodingMode.ALFANUMERIC]: 640, [EncodingMode.BYTE]: 439, [EncodingMode.KANJI]: 270 } },
    23: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 2620, [EncodingMode.ALFANUMERIC]: 1588, [EncodingMode.BYTE]: 1091, [EncodingMode.KANJI]: 672 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 2059, [EncodingMode.ALFANUMERIC]: 1248, [EncodingMode.BYTE]: 857, [EncodingMode.KANJI]: 528 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1468, [EncodingMode.ALFANUMERIC]: 890, [EncodingMode.BYTE]: 611, [EncodingMode.KANJI]: 376 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1108, [EncodingMode.ALFANUMERIC]: 672, [EncodingMode.BYTE]: 461, [EncodingMode.KANJI]: 284 } },
    24: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 2812, [EncodingMode.ALFANUMERIC]: 1704, [EncodingMode.BYTE]: 1171, [EncodingMode.KANJI]: 721 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 2188, [EncodingMode.ALFANUMERIC]: 1326, [EncodingMode.BYTE]: 911, [EncodingMode.KANJI]: 561 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1588, [EncodingMode.ALFANUMERIC]: 963, [EncodingMode.BYTE]: 661, [EncodingMode.KANJI]: 407 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1228, [EncodingMode.ALFANUMERIC]: 744, [EncodingMode.BYTE]: 511, [EncodingMode.KANJI]: 315 } },
    25: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 3057, [EncodingMode.ALFANUMERIC]: 1853, [EncodingMode.BYTE]: 1273, [EncodingMode.KANJI]: 784 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 2395, [EncodingMode.ALFANUMERIC]: 1451, [EncodingMode.BYTE]: 997, [EncodingMode.KANJI]: 614 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1718, [EncodingMode.ALFANUMERIC]: 1041, [EncodingMode.BYTE]: 715, [EncodingMode.KANJI]: 440 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1286, [EncodingMode.ALFANUMERIC]: 779, [EncodingMode.BYTE]: 535, [EncodingMode.KANJI]: 330 } },
    26: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 3283, [EncodingMode.ALFANUMERIC]: 1990, [EncodingMode.BYTE]: 1367, [EncodingMode.KANJI]: 842 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 2544, [EncodingMode.ALFANUMERIC]: 1542, [EncodingMode.BYTE]: 1059, [EncodingMode.KANJI]: 652 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1804, [EncodingMode.ALFANUMERIC]: 1094, [EncodingMode.BYTE]: 751, [EncodingMode.KANJI]: 462 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1425, [EncodingMode.ALFANUMERIC]: 864, [EncodingMode.BYTE]: 593, [EncodingMode.KANJI]: 365 } },
    27: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 3517, [EncodingMode.ALFANUMERIC]: 2132, [EncodingMode.BYTE]: 1465, [EncodingMode.KANJI]: 902 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 2701, [EncodingMode.ALFANUMERIC]: 1637, [EncodingMode.BYTE]: 1125, [EncodingMode.KANJI]: 692 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 1933, [EncodingMode.ALFANUMERIC]: 1172, [EncodingMode.BYTE]: 805, [EncodingMode.KANJI]: 496 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1501, [EncodingMode.ALFANUMERIC]: 910, [EncodingMode.BYTE]: 625, [EncodingMode.KANJI]: 385 } },
    28: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 3669, [EncodingMode.ALFANUMERIC]: 2223, [EncodingMode.BYTE]: 1528, [EncodingMode.KANJI]: 940 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 2857, [EncodingMode.ALFANUMERIC]: 1732, [EncodingMode.BYTE]: 1190, [EncodingMode.KANJI]: 732 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 2085, [EncodingMode.ALFANUMERIC]: 1263, [EncodingMode.BYTE]: 868, [EncodingMode.KANJI]: 534 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1581, [EncodingMode.ALFANUMERIC]: 958, [EncodingMode.BYTE]: 658, [EncodingMode.KANJI]: 405 } },
    29: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 3909, [EncodingMode.ALFANUMERIC]: 2369, [EncodingMode.BYTE]: 1628, [EncodingMode.KANJI]: 1002 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 3035, [EncodingMode.ALFANUMERIC]: 1839, [EncodingMode.BYTE]: 1264, [EncodingMode.KANJI]: 778 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 2181, [EncodingMode.ALFANUMERIC]: 1322, [EncodingMode.BYTE]: 908, [EncodingMode.KANJI]: 559 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1677, [EncodingMode.ALFANUMERIC]: 1016, [EncodingMode.BYTE]: 698, [EncodingMode.KANJI]: 430 } },
    30: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 4158, [EncodingMode.ALFANUMERIC]: 2520, [EncodingMode.BYTE]: 1732, [EncodingMode.KANJI]: 1066 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 3289, [EncodingMode.ALFANUMERIC]: 1994, [EncodingMode.BYTE]: 1370, [EncodingMode.KANJI]: 843 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 2358, [EncodingMode.ALFANUMERIC]: 1429, [EncodingMode.BYTE]: 982, [EncodingMode.KANJI]: 604 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1782, [EncodingMode.ALFANUMERIC]: 1080, [EncodingMode.BYTE]: 742, [EncodingMode.KANJI]: 457 } },
    31: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 4417, [EncodingMode.ALFANUMERIC]: 2677, [EncodingMode.BYTE]: 1840, [EncodingMode.KANJI]: 1132 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 3486, [EncodingMode.ALFANUMERIC]: 2113, [EncodingMode.BYTE]: 1452, [EncodingMode.KANJI]: 894 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 2473, [EncodingMode.ALFANUMERIC]: 1499, [EncodingMode.BYTE]: 1030, [EncodingMode.KANJI]: 634 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 1897, [EncodingMode.ALFANUMERIC]: 1150, [EncodingMode.BYTE]: 790, [EncodingMode.KANJI]: 486 } },
    32: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 4686, [EncodingMode.ALFANUMERIC]: 2840, [EncodingMode.BYTE]: 1952, [EncodingMode.KANJI]: 1201 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 3693, [EncodingMode.ALFANUMERIC]: 2238, [EncodingMode.BYTE]: 1538, [EncodingMode.KANJI]: 947 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 2670, [EncodingMode.ALFANUMERIC]: 1618, [EncodingMode.BYTE]: 1112, [EncodingMode.KANJI]: 684 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 2022, [EncodingMode.ALFANUMERIC]: 1226, [EncodingMode.BYTE]: 842, [EncodingMode.KANJI]: 518 } },
    33: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 4965, [EncodingMode.ALFANUMERIC]: 3009, [EncodingMode.BYTE]: 2068, [EncodingMode.KANJI]: 1273 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 3909, [EncodingMode.ALFANUMERIC]: 2369, [EncodingMode.BYTE]: 1628, [EncodingMode.KANJI]: 1002 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 2805, [EncodingMode.ALFANUMERIC]: 1700, [EncodingMode.BYTE]: 1168, [EncodingMode.KANJI]: 719 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 2157, [EncodingMode.ALFANUMERIC]: 1307, [EncodingMode.BYTE]: 898, [EncodingMode.KANJI]: 553 } },
    34: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 5253, [EncodingMode.ALFANUMERIC]: 3183, [EncodingMode.BYTE]: 2188, [EncodingMode.KANJI]: 1347 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 4134, [EncodingMode.ALFANUMERIC]: 2506, [EncodingMode.BYTE]: 1722, [EncodingMode.KANJI]: 1060 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 2949, [EncodingMode.ALFANUMERIC]: 1787, [EncodingMode.BYTE]: 1228, [EncodingMode.KANJI]: 756 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 2301, [EncodingMode.ALFANUMERIC]: 1394, [EncodingMode.BYTE]: 958, [EncodingMode.KANJI]: 590 } },
    35: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 5529, [EncodingMode.ALFANUMERIC]: 3351, [EncodingMode.BYTE]: 2303, [EncodingMode.KANJI]: 1417 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 4343, [EncodingMode.ALFANUMERIC]: 2632, [EncodingMode.BYTE]: 1809, [EncodingMode.KANJI]: 1113 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 3081, [EncodingMode.ALFANUMERIC]: 1867, [EncodingMode.BYTE]: 1283, [EncodingMode.KANJI]: 790 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 2361, [EncodingMode.ALFANUMERIC]: 1431, [EncodingMode.BYTE]: 983, [EncodingMode.KANJI]: 605 } },
    36: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 5836, [EncodingMode.ALFANUMERIC]: 3537, [EncodingMode.BYTE]: 2431, [EncodingMode.KANJI]: 1496 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 4588, [EncodingMode.ALFANUMERIC]: 2780, [EncodingMode.BYTE]: 1911, [EncodingMode.KANJI]: 1176 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 3244, [EncodingMode.ALFANUMERIC]: 1966, [EncodingMode.BYTE]: 1351, [EncodingMode.KANJI]: 832 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 2524, [EncodingMode.ALFANUMERIC]: 1530, [EncodingMode.BYTE]: 1051, [EncodingMode.KANJI]: 647 } },
    37: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 6153, [EncodingMode.ALFANUMERIC]: 3729, [EncodingMode.BYTE]: 2563, [EncodingMode.KANJI]: 1577 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 4775, [EncodingMode.ALFANUMERIC]: 2894, [EncodingMode.BYTE]: 1989, [EncodingMode.KANJI]: 1224 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 3417, [EncodingMode.ALFANUMERIC]: 2071, [EncodingMode.BYTE]: 1423, [EncodingMode.KANJI]: 876 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 2625, [EncodingMode.ALFANUMERIC]: 1591, [EncodingMode.BYTE]: 1093, [EncodingMode.KANJI]: 673 } },
    38: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 6479, [EncodingMode.ALFANUMERIC]: 3927, [EncodingMode.BYTE]: 2699, [EncodingMode.KANJI]: 1661 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 5039, [EncodingMode.ALFANUMERIC]: 3054, [EncodingMode.BYTE]: 2099, [EncodingMode.KANJI]: 1292 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 3599, [EncodingMode.ALFANUMERIC]: 2181, [EncodingMode.BYTE]: 1499, [EncodingMode.KANJI]: 923 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 2735, [EncodingMode.ALFANUMERIC]: 1658, [EncodingMode.BYTE]: 1139, [EncodingMode.KANJI]: 701 } },
    39: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 6743, [EncodingMode.ALFANUMERIC]: 4087, [EncodingMode.BYTE]: 2809, [EncodingMode.KANJI]: 1729 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 5313, [EncodingMode.ALFANUMERIC]: 3220, [EncodingMode.BYTE]: 2213, [EncodingMode.KANJI]: 1362 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 3791, [EncodingMode.ALFANUMERIC]: 2298, [EncodingMode.BYTE]: 1579, [EncodingMode.KANJI]: 972 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 2927, [EncodingMode.ALFANUMERIC]: 1774, [EncodingMode.BYTE]: 1219, [EncodingMode.KANJI]: 750 } },
    40: { [ErrorCorrection.L]: { [EncodingMode.NUMERIC]: 7089, [EncodingMode.ALFANUMERIC]: 4296, [EncodingMode.BYTE]: 2953, [EncodingMode.KANJI]: 1817 }, [ErrorCorrection.M]: { [EncodingMode.NUMERIC]: 5596, [EncodingMode.ALFANUMERIC]: 3391, [EncodingMode.BYTE]: 2331, [EncodingMode.KANJI]: 1435 }, [ErrorCorrection.Q]: { [EncodingMode.NUMERIC]: 3993, [EncodingMode.ALFANUMERIC]: 2420, [EncodingMode.BYTE]: 1663, [EncodingMode.KANJI]: 1024 }, [ErrorCorrection.H]: { [EncodingMode.NUMERIC]: 3057, [EncodingMode.ALFANUMERIC]: 1852, [EncodingMode.BYTE]: 1273, [EncodingMode.KANJI]: 784 } },
}
